name: pythonCI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - click
  - Flask
  - itsdangerous
  - Jinja2
  - MarkupSafe
  - numpy
  - pandas
  - python-dateutil
  - pytz
  - scikit-learn
  - scipy
  - six
  - Werkzeug
  - pytest
  - pip
  - joblib
  - flask-restful
  - pip:
    - mlflow
    - flask_restful
    